### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by Vangor** [MariusRumpf/copy-filename#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [copy-filename](https://github.com/mariusrumpf/copy-filename) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /.atom/packages/copy-filename/lib/copy-filename.js:53

TypeError: Cannot read property 'file' of undefined
    at Object.copyOpenFile (/packages/copy-filename/lib/copy-filename.js:53:27)
    at HTMLElement.copyFilenameCopyOpenFileFilename (/packages/copy-filename/lib/copy-filename.js:14:19)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -8:03.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -7:37.1.0 core:backspace (input.hidden-input)
     -7:36.7.0 core:move-left (input.hidden-input)
     -7:31.4.0 core:save (input.hidden-input)
     -7:13.9.0 core:copy (input.hidden-input)
     -6:57.7.0 core:backspace (input.hidden-input)
  4x -6:57.1.0 core:move-right (input.hidden-input)
     -6:51.3.0 core:copy (input.hidden-input)
     -6:27.6.0 snippets:next-tab-stop (input.hidden-input)
     -6:27.6.0 snippets:expand (input.hidden-input)
     -6:27.6.0 editor:indent (input.hidden-input)
     -0:10.5.0 core:paste (input.hidden-input)
     -0:09.5.0 core:undo (input.hidden-input)
     -0:05.9.0 copy-filename:copy-open-file-filename (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-ide-ui 0.6.0 
autocomplete-paths 2.12.1 
chrome-color-picker 0.8.0 
copy-filename 1.1.0 
coverage-markers 0.3.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.14 
git-blame 1.3.1 
gitkraken 0.4.3 
highlight-selected 0.13.1 
ide-typescript 0.7.0 
language-babel 2.79.0 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
linter-eslint 8.4.0 
linter-stylelint 4.0.2 
local-history 4.3.1 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
tester 1.4.0 
tester-jest 1.1.8 
```

**Comment by mhulse** [comment]
Same, and when I right click in sidebar and choose Copy filename, it doesn't copy the file name. :(

This was working up until a few months ago from what I recall. 

Unfortunately, not seeing alternative packages. If I had time, I'd dig in deeper and do a PR. I'll see if I can look at this sometime in next couple weeks.

**Comment by MariusRumpf** [comment]
52eba34fc1b1cb83f9674ff948ce472fc274f66f should fix the issue. Just published version 1.2.0 to apm.

**Comment by mhulse** [comment]
Thanks!!!! Much appreciated.
